[tools]
gitleaks = "latest"
just = "latest"
pre-commit = "latest"
ruff = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"
pkl = "latest"
shfmt = "latest"
shellcheck = "latest"
eza = "latest"
prettier = "latest"

[hooks.enter]
shell = "bash"
script = "mise i -q"

[env]
REPO = "{{ config_root | absolute }}"
REPO_NAME = "{{ config_root | basename }}"

HK_MISE = 1
HK_LIBGIT2 = 0
MISE_NPM_BUN = 1

[tasks.pre-commit]
alias = "pc"
run = "hk run pre-commit"
