[tool.uv]
workspace.members = ["packages/*"]

[tool.mypy]
packages = ["traefik", "winterm"]
exclude = ["deprecated"]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "detect-secrets>=1.5.0",
    "mypy>=1.18.2",
    "ruff>=0.14.6",
    "ty>=0.0.1a27",
    "types-pyyaml>=6.0.12.20250915",
    "types-requests>=2.32.4.20250913",
    "uv-build>=0.9.11",
]

[tool.ty.environment]
root = ["./packages"]
