[tools]
just = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"
fnox = "latest"

[env]
OP_RUN_NO_MASKING = true
COMPOSE_BAKE = true
SYNC_MODE = "cron"

TZ = "America/Chicago"
PUID = 1000
PGID = 1000

# compose host
DOCKER_HOST = "tcp://192.168.1.70:2375"
REGISTRY = "forgejo.henn.dev/chris"
DHOST_SSH = "ssh chris@192.168.1.70 -p 22"

# paths to homelab repo on host
REPO = "/home/chris/Projects/homelab/"
REPO_MACHINE = "/home/chris/Projects/homelab/rack0"

# paths to data
DATA = "/mnt/k/docker"

SVC_IP = "192.168.1.70"
DNS_VIP = "192.168.1.3"
TRAEFIK_VIP = "192.168.1.4"
