http:
  middlewares:
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: 'none,noarchive,nosnippet,notranslate,noimageindex'
          X-Forwarded-Proto: 'https'
          server: ''
        customRequestHeaders:
          X-Forwarded-Proto: 'https'
        sslProxyHeaders:
          X-Forwarded-Proto: 'https'
        referrerPolicy: 'same-origin'
        hostsProxyHeaders:
          - 'X-Forwarded-Host'
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
