networks:
  docker:
    name: docker
    driver: bridge
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: $FRONTEND_SUBNET
          gateway: $FRONTEND

include:
  - apps/actual.yml
  - apps/apprise.yml
  - apps/backrest.yml
  - apps/beszel.yml
  - apps/bytestash.yml
  - apps/calibre.yml
  - apps/chartdb.yml
  - apps/code.yml
  - apps/cognito.yml
  - apps/comfy.yml
  - apps/convertx.yml
  - apps/aptcache.yml
  - apps/blocky.yml
  - apps/blocky_k.yml
  - apps/lancache.yml
  - apps/portainer.yml
  - apps/rebuild.yml
  - apps/socket-proxy.yml
  - apps/traefik.yml
  - apps/traefik_k.yml
  - apps/cyberchef.yml
  - apps/docmost.yml
  - apps/dozzle.yml
  - apps/dumb.yml
  - apps/excalidraw.yml
  - apps/files.yml
  - apps/ghrunner.yml
  - apps/gist.yml
  - apps/gluetun.yml
  - apps/gocron.yml
  - apps/gotify.yml
  - apps/fileflow.yml
  - apps/hedge.yml
  - apps/immich.yml
  - apps/forgejo.yml
  - apps/homepage.yml
  - apps/kuma.yml
  - apps/watchtower.yml
  - apps/ittools.yml
  - apps/kestra.yml
  - apps/linkstack.yml
  - apps/littlelink.yml
  - apps/matrix.yml
  - apps/audiobookshelf.yml
  - apps/bazarr.yml
  - apps/jellyfin.yml
  - apps/jellyseerr.yml
  - apps/lidarr.yml
  - apps/prowlarr.yml
  - apps/radarr.yml
  - apps/recyclarr.yml
  - apps/solverr.yml
  - apps/sonarr.yml
  - apps/metube.yml
  - apps/minio.yml
  - apps/n8n.yml
  - apps/navidrome.yml
  - apps/netboot.yml
  - apps/nexterm.yml
  - apps/ntfy.yml
  - apps/ollama.yml
  - apps/omni.yml
  - apps/openresume.yml
  - apps/openspeedtest.yml
  - apps/openwebui.yml
  - apps/owncast.yml
  - apps/pairdrop.yml
  - apps/paperless.yml
  - apps/perplexica.yml
  - apps/qbit.yml
  - apps/sab.yml
  - apps/searx.yml
  - apps/speach.yml
  - apps/stirling.yml
  - apps/termix.yml
  - apps/tududi.yml
  - apps/vert.yml
  - apps/wastebin.yml
  - apps/librespeed.yml
  - apps/rxresume.yml
  - apps/rsync.yml
  - apps/focalboard.yml
  - apps/planka.yml
  - apps/game.yml
  - apps/gitlab.yml
  - apps/gitlab_runner.yml
  - apps/nginx.yml
  - apps/newt.yml
  - apps/ldr.yml
