networks:
  docker:
    name: docker
    driver: bridge
  traefik:
    name: traefik
    driver: bridge
    ipam:
      config:
        - subnet: $FRONTEND_SUBNET
          gateway: $FRONTEND

include:
  - apps/backup/backrest.yml
  - apps/backup/rsync.yml

  - apps/dev/bytestash.yml
  - apps/dev/chartdb.yml
  - apps/dev/code.yml
  - apps/dev/cyberchef.yml
  - apps/dev/dumb.yml
  - apps/dev/excalidraw.yml
  - apps/dev/focalboard.yml
  - apps/dev/forgejo.yml
  - apps/dev/gist.yml
  - apps/dev/gitlab.yml
  - apps/dev/ittools.yml

  - apps/document/convertx.yml
  - apps/document/docmost.yml
  - apps/document/documenso.yml
  - apps/document/filebrowser.yml
  - apps/document/hedge.yml
  - apps/document/nextcloud.yml
  - apps/document/omni.yml
  - apps/document/openresume.yml
  - apps/document/pairdrop.yml
  - apps/document/paperless.yml
  - apps/document/rxresume.yml
  - apps/document/stirling.yml
  - apps/document/vert.yml

  - apps/infra/apprise.yml
  - apps/infra/aptcache.yml
  - apps/infra/arcane.yml
  - apps/infra/beszel.yml
  - apps/infra/blocky.yml
  - apps/infra/blocky_k.yml
  - apps/infra/dozzle.yml
  - apps/infra/gocron.yml
  - apps/infra/gotify.yml
  - apps/infra/homepage.yml
  - apps/infra/kuma.yml
  - apps/infra/lancache.yml
  - apps/infra/librespeed.yml
  - apps/infra/netboot.yml
  - apps/infra/newt.yml
  - apps/infra/nexterm.yml
  - apps/infra/ntfy.yml
  - apps/infra/openspeedtest.yml
  - apps/infra/pocketid.yml
  - apps/infra/socket-proxy.yml
  - apps/infra/termix.yml
  - apps/infra/traefik.yml
  - apps/infra/traefik_k.yml

  - apps/media/audiobookshelf.yml
  - apps/media/bazarr.yml
  - apps/media/calibre.yml
  - apps/media/immich.yml
  - apps/media/jellyfin.yml
  - apps/media/seerr.yml
  - apps/media/lidarr.yml
  - apps/media/metube.yml
  - apps/media/navidrome.yml
  - apps/media/prowlarr.yml
  - apps/media/qbit.yml
  - apps/media/qui.yml
  - apps/media/radarr.yml
  - apps/media/recyclarr.yml
  - apps/media/sab.yml
  - apps/media/solverr.yml
  - apps/media/sonarr.yml

  - apps/actual.yml
  - apps/airtrail.yml
  - apps/cognito.yml
  - apps/comfy.yml
  - apps/fileflow.yml
  - apps/game.yml
  - apps/karakeep.yml
  - apps/kestra.yml
  - apps/ldr.yml
  - apps/linkding.yml
  - apps/linkstack.yml
  - apps/littlelink.yml
  - apps/matrix.yml
  - apps/memos.yml
  - apps/n8n.yml
  - apps/ollama.yml
  - apps/openwebui.yml
  - apps/owncast.yml
  - apps/perplexica.yml
  - apps/planka.yml
  - apps/rally.yml
  - apps/searx.yml
  - apps/speach.yml
  - apps/tududi.yml
  - apps/vikunja.yml
  - apps/warden.yml
  - apps/zulip.yml
  - apps/miro.yml
  - apps/seafile.yml
