[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[secrets]
OP_SERVICE_ACCOUNT_TOKEN = { provider = "onepass", value = "op://homelab/osuyuc25hlprsxvfrlajni7sqa/credential" }

USER = { provider = "onepass", value = "op://homelab/chris/username" }
PASS = { provider = "onepass", value = "op://homelab/chris/password" }
EMAIL = { provider = "onepass", value = "op://homelab/chris/email" }

CF_API_EMAIL = { provider = "onepass", value = "op://homelab/cloudflare_token/username" }
CF_DNS_API_TOKEN = { provider = "onepass", value = "op://homelab/cloudflare_token/credential" }

BESZEL_KEY = { provider = "onepass", value = "op://homelab/beszel/key" }
BESZEL_TOKEN = { provider = "onepass", value = "op://homelab/beszel/token" }

DOCKERHUB_USER = { provider = "onepass", value = "op://homelab/dockerhub/username" }
DOCKERHUB_PASS = { provider = "onepass", value = "op://homelab/dockerhub/password" }

RADARR_URL = { provider = "onepass", value = "op://homelab/radarr/url" }
RADARR_KEY = { provider = "onepass", value = "op://homelab/radarr/credential" }
SONARR_URL = { provider = "onepass", value = "op://homelab/sonarr/url" }
SONARR_KEY = { provider = "onepass", value = "op://homelab/sonarr/credential" }

GHRUNNER_PAT = { provider = "onepass", value = "op://homelab/ghrunner/credential" }
GL_RUNNER_TOKEN = { provider = "onepass", value = "op://homelab/Gitlab/runner_token" }
GL_RUNNER_TOKEN2 = { provider = "onepass", value = "op://homelab/Gitlab/runner_token2" }

HARDCOVER_TOKEN = { provider = "onepass", value = "op://homelab/Hardcover/api_token" }
NEXTERM_ENCRYPTION_KEY = { provider = "onepass", value = "op://homelab/nexterm/credential" }
TUDUDI_SECRET = { provider = "onepass", value = "op://homelab/tududi/credential" }
SEARXNG_SECRET = { provider = "onepass", value = "op://homelab/searxng/credential" }
WIREGUARD_PRIVATE_KEY = { provider = "onepass", value = "op://homelab/proton/VPN/wireguard_private_key" }
NEXTCLOUD_HARP_KEY = { provider = "onepass", value = "op://homelab/Nextcloud/harp_key" }

DOCMOST_SECRET = { provider = "onepass", value = "op://homelab/docmost/credential" }
DOCMOST_DBURL = { provider = "onepass", value = "op://homelab/docmost/dburl" }

RXRESUME_AUTH_SECRET = { provider = "onepass", value = "op://homelab/rxresume/credential" }
RXRESUME_PGURL = { provider = "onepass", value = "op://homelab/rxresume/pgurl" }

PAPERLESS_SECRET_KEY = { provider = "onepass", value = "op://homelab/paperless/secret_key" }
PAPERLESS_TOKEN = { provider = "onepass", value = "op://homelab/paperless/credential" }

PANGOLIN_ENDPOINT = { provider = "onepass", value = "op://homelab/Pangolin-Hostinger/PANGOLIN_ENDPOINT" }
NEWT_ID = { provider = "onepass", value = "op://homelab/Pangolin-Hostinger/NEWT_ID" }
NEWT_SECRET = { provider = "onepass", value = "op://homelab/Pangolin-Hostinger/NEWT_SECRET" }

SMTP_HOST = { provider = "onepass", value = "op://homelab/proton/SMTP/smtp_host" }
SMTP_USER = { provider = "onepass", value = "op://homelab/proton/SMTP/smtp_user" }
SMTP_TOKEN = { provider = "onepass", value = "op://homelab/proton/SMTP/smtp_token" }

DOCU_SECRET = { provider = "onepass", value = "op://homelab/Documenso/DOCU_SECRET" }
DOCU_ENCRYPTION_KEY = { provider = "onepass", value = "op://homelab/Documenso/DOCU_ENCRYPTION_KEY" }
DOCU_ENCRYPTION_SECOND_KEY = { provider = "onepass", value = "op://homelab/Documenso/DOCU_ENCRYPTION_SECOND_KEY" }
DOCU_SIGNING_PASS = { provider = "onepass", value = "op://homelab/Documenso/DOCU_SIGNING_PASS" }

WASABI_URL = { provider = "onepass", value = "op://homelab/wasabi/wasabi_url" }
WASABI_ACCESS_KEY = { provider = "onepass", value = "op://homelab/wasabi/access_key" }
WASABI_SECRET_KEY = { provider = "onepass", value = "op://homelab/wasabi/secret_key" }
WASABI_RESTIC_PASSWORD = { provider = "onepass", value = "op://homelab/wasabi/wasabi_restic_password" }

GDRIVE_CLIENT_ID = { provider = "onepass", value = "op://homelab/gdrive/client_id" }
GDRIVE_CLIENT_SECRET = { provider = "onepass", value = "op://homelab/gdrive/client_secret" }
GDRIVE_ACCESS_TOKEN = { provider = "onepass", value = "op://homelab/gdrive/access_token" }

RCLONE_FILEN_EMAIL = { provider = "onepass", value = "op://homelab/filen/username" }
RCLONE_FILEN_PASSWORD = { provider = "onepass", value = "op://homelab/filen/password_obs" }
RCLONE_FILEN_API_KEY = { provider = "onepass", value = "op://homelab/filen/api_key_obs" }

FILEN_EMAIL = { provider = "onepass", value = "op://homelab/filen/username" }
FILEN_PASSWORD = { provider = "onepass", value = "op://homelab/filen/password" }
FILEN_2FA_CODE = { provider = "onepass", value = "op://homelab/Filen/2fa_recovery" }

HOSTINGERIP = { provider = "onepass", value = "op://homelab/nlptoaczq3qtw2fqs6nb2d6r5y/hostinger_ip" }

COLLABORA_AUTH_USER = { provider = "onepass", value = "op://homelab/collabora/username" }
COLLABORA_AUTH_PASS = { provider = "onepass", value = "op://homelab/collabora/credential" }
