[providers.onepass]
type = "1password"
vault = "homelab"
account = "my.1password.com"

[secrets]
VPS0_IP = { provider = "onepass", value = "op://homelab/vps0/ip" }
CLOUDFLARE_API_TOKEN = { provider = "onepass", value = "op://homelab/cloudflare_token/credential" }
ZONEID = { provider = "onepass", value = "op://homelab/cloudflare_token/zoneid_chenndev" }
