[settings]
python.uv_venv_auto = "create|source"

[env]
SSH_ROOT = "ssh root@{{env.HOSTINGERIP}}"
SSH_CHRIS = "ssh chris@{{env.HOSTINGERIP}} -p 2200"

[tools]
fnox = "latest"
pulumi = "latest"
uv = "latest"
