[env]
SSH_ROOT = "ssh root@{{env.HOSTINGERIP}}"
SSH_CHRIS = "ssh chris@{{env.HOSTINGERIP}} -p 2200"

[tools]
fnox = "latest"
pulumi = "latest"
uv = "latest"

[hooks.enter]
shell = "bash"
script = """
    mise i -q \
    && [ -d .venv ] || uv venv --allow-existing \
    && source .venv/bin/activate --active \
    && uv sync
    """
