# note that these are only scanning for _new_ secrets on commit - there are still secrets in the git history
# note that you can just choose one of these to scan for secrets before commit
repos:
    - repo: local
      hooks:
#      - id: trufflehog
#        name: trufflehog
#        description: Detect secrets in your repo before committing them
#        entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail --no-update'
#        language: system
#        stages: ["pre-commit"]
#      - id: git-secrets
#        name: git-secrets
#        description: git-secrets scans commits, commit messages, and --no-ff merges to prevent committing secrets
#        entry: bash -c 'git-secrets . --pre_commit_hook'
#        language: system
#        stages: ["pre-commit"]
#      - id: detect-secrets
#        name: detect-secrets
#        entry: bash -c "detect-secrets-hook --baseline .secrets.baseline"
#        exclude: package.lock.json
#        language: system
#        stages: ["pre-commit"]
#      - id: gitleaks
#        name: gitleaks
#        entry: bash -c 'mise x -- gitleaks git . --pre-commit'
#        language: system
#        stages: ["pre-commit"]
#      - id: sort-simple-yaml
#      - id: detect-private-key
#      - id: check-merge-conflict
#      - id: end-of-file-fixer
#      - id: mixed-line-ending
#      - id: trailing-whitespace
#        args: [--markdown-linebreak-ext=md]
#  - repo: https://github.com/adrienverge/yamllint.git
#    rev: v1.33.0
#    hooks:
#      - id: yamllint
#        args: [-c=.yamllint]
#  - repo: https://github.com/ansible-community/ansible-lint.git
#    rev: v6.22.2
#    hooks:
#      - id: ansible-lint
#  - repo: https://github.com/shellcheck-py/shellcheck-py
#    rev: v0.9.0.6
#    hooks:
#      - id: shellcheck
#  - repo: https://github.com/Lucas-C/pre-commit-hooks
#    rev: v1.5.4
#    hooks:
#      - id: remove-crlf
#      - id: remove-tabs
#  - repo: https://github.com/sirosen/texthooks
#    rev: 0.6.4
#    hooks:
#      - id: fix-smartquotes
