[tools]
just = "latest"
fnox = "latest"

[env]
OP_RUN_NO_MASKING = true
COMPOSE_BAKE = true

TZ = "America/Chicago"
PUID = 1000
PGID = 1000

# compose host
DOCKER_HOST = "tcp://192.168.1.142:2375"
DHOST_SSH = "ssh chris@192.168.1.142 -p 2200"

# paths to data
DATA = "/mnt/k/docker"

# docker frontend subnet
FRONTEND = "192.168.200.1"
FRONTEND_SUBNET = "192.168.200.0/24"

# host ip to bind services to
SVCIP = "192.168.1.144"
