---
services:
  win-builder:
    image: christianhenn/win-builder:latest
    build: .
    container_name: win-builder
    hostname: win-builder
    network_mode: nat
    restart: 'no'
    mem_limit: 32g
    cpus: 12
    working_dir: C:\project
    volumes:
      - C:\project:C:\project
