---
services:
  windows-7:
    image: chrishenn/dockurr:latest
    container_name: windows-7
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VERSION: 'win7x64-ultimate'
      RAM_SIZE: '16G'
      CPU_CORES: '8'
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - '8006:8006'
      - '3389:3389/tcp'
      - '3389:3389/udp'
    stop_grace_period: 2m
    restart: unless-stopped
    volumes:
      - /home/chris/dockurr/win7:/storage
  windows-81:
    image: chrishenn/dockurr:latest
    container_name: windows-81
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VERSION: 'win81x64'
      RAM_SIZE: '16G'
      CPU_CORES: '8'
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - '8006:8006'
      - '3389:3389/tcp'
      - '3389:3389/udp'
    stop_grace_period: 2m
    restart: unless-stopped
    volumes:
      - /home/chris/dockurr/win81:/storage
  windows-11:
    image: dockurr/windows:latest
    container_name: windows-11
    environment:
      VERSION: 'win11x64'
      RAM_SIZE: '16G'
      CPU_CORES: '8'
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - '8006:8006'
      - '3389:3389/tcp'
      - '3389:3389/udp'
    stop_grace_period: 2m
    restart: unless-stopped
    volumes:
      - /home/chris/dockurr/win11:/storage
