# https://ssl-config.mozilla.org/#server: traefik&version: 3.5&config: modern&guideline: 5.6
http:
  middlewares:
    hdrs:
      headers:
        customResponseHeaders:
          X-Robots-Tag: 'noindex,nofollow'
          X-Forwarded-Proto: 'https'
          server: ''
          X-Powered-By: ''
        customRequestHeaders:
          X-Forwarded-Proto: 'https'
          Strict-Transport-Security: 'max-age: 63072000'
        sslProxyHeaders:
          X-Forwarded-Proto: 'https'
        hostsProxyHeaders:
          - 'X-Forwarded-Host'
        referrerPolicy: 'same-origin'
        contentTypeNosniff: true
        browserXssFilter: true
        customFrameOptionsValue: 'SAMEORIGIN'
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
        addvaryheader: true
        sslredirect: true
        sslforcehost: true
        featurepolicy: |
          camera 'none';
          geolocation 'none';
          microphone 'none';
          payment 'none';
          usb 'none';
          vr 'none';
