global:
  checkNewVersion: true
  sendAnonymousUsage: false

experimental:
  plugins:
    oidc:
      moduleName: 'github.com/sevensolutions/traefik-oidc-auth'
      version: 'v0.18.0'

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
  insecure: true

providers:
  providersThrottleDuration: 2s
  file:
    directory: /cfg
    watch: true
  docker:
    watch: true
    network: traefik
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false

tls:
  options:
    default:
      minVersion: VersionTLS13
      curvePreferences:
        - 'X25519'
        - 'CurveP256'
        - 'CurveP384'

http:
  encodedCharacters:
    allowEncodedSlash: true
    allowEncodedBackSlash: false
    allowEncodedNullCharacter: false
    allowEncodedSemicolon: false
    allowEncodedPercent: false
    allowEncodedQuestionMark: true
    allowEncodedHash: false

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        - 127.0.0.1/32
        - 172.16.0.0/16
        - 192.168.0.0/16
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    transport:
      respondingTimeouts:
        readTimeout: '30m'
        writeTimeout: '30m'
        idleTimeout: '30m'
    forwardedHeaders:
      trustedIPs: *trustedIps
    http:
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedBackSlash: false
        allowEncodedNullCharacter: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: true
        allowEncodedHash: false
      tls:
        certResolver: cf
        domains:
          - main: henn.dev
            sans:
              - '*.henn.dev'
  tcp-2222:
    address: ':2222'
  tcp-2424:
    address: ':2424'
  rtmp:
    address: ':1935'
  spice:
    address: ':3128'
  spice-tls:
    address: ':61001'
  udp-10000:
    address: ':10000/udp'

certificatesResolvers:
  cf:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '1.0.0.1:53'
      email: 'christopherpenn1000@gmail.com'
      storage: /ssl/acme.json
      caServer: 'https://acme-v02.api.letsencrypt.org/directory'

log:
  level: DEBUG
  format: common
  compress: true

ping: {}
