# works great, but using opengist instead
---
services:
  wastebin:
    profiles: [wastebin]
    image: quxfoo/wastebin:latest
    container_name: wastebin
    restart: unless-stopped
    networks: [traefik]
    labels:
      homepage.instance.private.group: Code
      homepage.instance.private.name: Wastebin
      homepage.instance.private.icon: pastebin-dark.webp
      homepage.instance.private.href: https://wastebin.henn.dev
      homepage.instance.private.description: Pastebin

      traefik.enable: true
      traefik.http.routers.wastebin.rule: Host(`wastebin.henn.dev`)
      traefik.http.routers.wastebin.entrypoints: websecure
      traefik.http.routers.wastebin.middlewares: hdrs@file
      traefik.http.routers.wastebin.tls.certresolver: cf
      traefik.http.services.wastebin.loadbalancer.server.port: 8088
